# Generated by Django 5.1.1 on 2024-11-06 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rating",
            field=models.FloatField(
                blank=True,
                help_text="min: 1, max: 5",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="rating (1-5)",
            ),
        ),
    ]
