# Generated by Django 5.1.1 on 2024-09-22 12:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('birst_day', models.DateField(verbose_name='birst day')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('autor_type', models.CharField(choices=[('owner', 'owner'), ('agent', 'agent'), ('rentner', 'rentner')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('apartment', 'apartment'), ('villa', 'villa'), ('studio', 'studio'), ('townhouse', 'townhouse'), ('duplex', 'duplex')], default='apartment', max_length=20, verbose_name='typeOfHousing')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200, verbose_name='locations')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_rooms', models.PositiveSmallIntegerField(max_length=100, verbose_name='count rooms')),
                ('available', models.BooleanField(default=True)),
                ('rating', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='rating')),
                ('register_date', models.DateField(auto_now_add=True)),
                ('available_date', models.DateField(verbose_name='available date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiForRent.category')),
            ],
        ),
    ]
