# Generated by Django 5.1.1 on 2024-09-22 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiForRent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='real_estate_image',
            field=models.ImageField(blank=True, null=True, upload_to='real_estate_images/'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='number_of_rooms',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='count rooms'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='realty',
            name='rating',
            field=models.FloatField(help_text='min:1,max:10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='rating (1-10)'),
        ),
    ]
