# Generated by Django 5.1.1 on 2024-09-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiForRent', '0002_realty_real_estate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='apiForRent.autor'),
        ),
    ]
