# Generated by Django 5.1.1 on 2024-10-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiForRent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.CharField(max_length=50)),
                ('garage_or_parking', models.CharField(max_length=50)),
                ('balcony', models.CharField(max_length=50)),
                ('heating_type', models.CharField(max_length=50)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('floor_number', models.PositiveIntegerField()),
                ('total_floors', models.PositiveIntegerField()),
                ('pet_friendly', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AlterModelOptions(
            name='realty',
            options={'ordering': ['-register_date', 'title']},
        ),
    ]
