# Generated by Django 5.1.1 on 2024-10-17 09:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiForRent', '0002_realtydetail_delete_autor_alter_realty_options'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='realty',
            name='class_realty',
            field=models.CharField(choices=[('standard', 'Стандарт'), ('economy', 'Эконом'), ('comfort', 'Комфорт'), ('premium', 'Премиум'), ('luxury', 'Люкс'), ('super_luxury', 'Супер-люкс')], default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='realty',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realty',
            name='real_estate_image',
            field=models.ImageField(blank=True, null=True, upload_to='real_estate_images/', verbose_name='main real estate picture'),
        ),
        migrations.AddField(
            model_name='realty',
            name='square_footage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='realty',
            name='available_date',
            field=models.DateField(verbose_name='availability date'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='description',
            field=models.TextField(verbose_name='property description'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='location',
            field=models.CharField(max_length=200, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='number_of_rooms',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of rooms'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='realty',
            name='rating',
            field=models.FloatField(help_text='min: 1, max: 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='realty',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiForRent.realtydetail'),
        ),
        migrations.AddIndex(
            model_name='realty',
            index=models.Index(fields=['register_date', 'title'], name='apiForRent__registe_d8291b_idx'),
        ),
        migrations.AddIndex(
            model_name='realty',
            index=models.Index(fields=['category'], name='apiForRent__categor_9313ee_idx'),
        ),
    ]
