# Generated by Django 5.1.1 on 2024-11-06 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apiForRent",
            "0003_realty_author_realty_class_realty_realty_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtyFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=100, null=True)),
                ("path", models.FileField(upload_to="realtyFiles/")),
                (
                    "realty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtyFiles",
                        to="apiForRent.realty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл недвижимости",
                "verbose_name_plural": "Файлы недвижимости",
                "ordering": ["realty"],
            },
        ),
    ]
