# Generated by Django 5.1.1 on 2024-11-13 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiForRent", "0005_alter_realty_author_alter_realtydetail_balcony_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="realty",
            name="favorite",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="favorite_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="realty",
            name="views",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="views_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
