# Generated by Django 5.1.1 on 2024-11-15 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiForRent", "0006_realty_favorite_realty_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="realty",
            name="reservations",
            field=models.ManyToManyField(
                blank=True,
                related_name="reserv_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="realty",
            name="details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="apiForRent.realtydetail",
            ),
        ),
        migrations.AlterField(
            model_name="realty",
            name="favorite",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="realty",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="views_properties", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="realtydetail",
            name="floor_number",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="realtydetail",
            name="furnished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="realtydetail",
            name="pet_friendly",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="realtydetail",
            name="total_floors",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
