# Generated by Django 5.1.1 on 2024-11-18 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiForRent", "0008_alter_realty_favorite_alter_realty_reservations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realty",
            name="price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="price",
            ),
        ),
    ]
