# Generated by Django 5.1.1 on 2024-11-19 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiForRent", "0009_alter_realty_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="realty",
            name="favorite",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="realty",
            name="reservations",
            field=models.ManyToManyField(
                blank=True,
                related_name="reserv_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="realty",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="views_properties", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "realty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apiForRent.realty",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="realty",
            name="booking_details",
            field=models.ManyToManyField(
                blank=True,
                related_name="booking_properties",
                through="apiForRent.Booking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
